### ISSUE TITLE
Not Able to Inference Through `Gradio`

### ISSUE THREAD

**Issue by nikithakriz** [JosefAlbers/Phi-3-Vision-MLX#8]
I just installed phi-3-vision-mlx in my M3 pro MacBook Pro using command:

`!pip install phi-3-vision-mlx`

then ran 
`!phi3v`

It downloaded the phi-3-vision model files correctly and after that the Gradio UI opened. But when I added the image to grade and tried to inference the error raises.
`pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type`

How can I fix this? 

Additionally it worked fine when I inference it directly from package(phi_3_vision_mlx) using `generate`

**Comment by JosefAlbers** [comment]
It looks like you're using this from a Jupyter notebook. I wonder if the issue you're experiencing could be related to that specific environment. To troubleshoot, I suggest running the command directly from your Terminal app instead of a Jupyter cell:

1. Open Terminal
2. Activate your conda environment (if you're using one)
3. Run the command:

    ```zsh
    phi3v
    ```

This should launch the Gradio interface without Jupyter-related complications. Let me know if you still encounter issues when running it this way.

**Comment by nikithakriz** [comment]
Tried it in terminal.
Activated venv in terminal(as am not using any condo environment)

still the same errors.
there are the packages installed in my venv

`pip freeze`

```
accelerate==0.34.2
aiofiles==23.2.1
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
altair==5.4.1
annotated-types==0.7.0
anyio==4.4.0
appnope==0.1.4
asttokens==2.4.1
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.3.2
click==8.1.7
comm==0.2.2
contourpy==1.3.0
cycler==0.12.1
datasets==2.19.1
debugpy==1.8.5
decorator==5.1.1
dill==0.3.8
executing==2.0.1
fastapi==0.114.0
ffmpy==0.4.0
filelock==3.15.4
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.3.1
gradio==4.31.5
gradio_client==0.16.4
h11==0.14.0
httpcore==1.0.5
httpx==0.27.2
huggingface-hub==0.24.6
idna==3.8
importlib_resources==6.4.4
ipykernel==6.29.5
ipython==8.27.0
jedi==0.19.1
Jinja2==3.1.4
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter_client==8.6.2
jupyter_core==5.7.2
kiwisolver==1.4.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
matplotlib-inline==0.1.7
mdurl==0.1.2
mlx==0.15.0
mpmath==1.3.0
multidict==6.0.5
multiprocess==0.70.16
narwhals==1.6.2
nest-asyncio==1.6.0
networkx==3.3
numpy==1.26.4
orjson==3.10.7
packaging==24.1
pandas==2.2.2
parso==0.8.4
pexpect==4.9.0
phi-3-vision-mlx==0.1.5
pillow==10.4.0
platformdirs==4.2.2
prompt_toolkit==3.0.47
psutil==6.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pyarrow==17.0.0
pyarrow-hotfix==0.6
pydantic==2.9.0
pydantic_core==2.23.2
pydub==0.25.1
Pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.2
pyzmq==26.2.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
rich==13.8.0
rpds-py==0.20.0
ruff==0.6.4
safetensors==0.4.5
semantic-version==2.10.0
setuptools==74.1.2
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
stack-data==0.6.3
starlette==0.38.4
sympy==1.13.2
tokenizers==0.19.1
tomlkit==0.12.0
torch==2.4.1
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
transformers==4.40.2
typer==0.12.5
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
uvicorn==0.30.6
wcwidth==0.2.13
websockets==11.0.3
xxhash==3.5.0
yarl==1.10.0
```

**Comment by colin4k** [comment]
`pip install -U gradio==4.43.0` can fix this error

**Comment by JosefAlbers** [comment]
> pip install -U gradio==4.43.0 can fix this error

Thanks!

**Comment by softwaredoug** [comment]
In the end, isn't this an issue with this project's dependencies, ie poetry would complain:

```
 $ poetry add gradio==4.43.0                                                                                                                                                                              

Updating dependencies
Resolving dependencies... (0.1s)

Because phi-3-vision-mlx (0.1.5) depends on gradio (4.31.5)
```

Of course we can force it outside of a tool like this, but this seems to be the core issue here
